volumes:
  - name: tls
    configMap:
      name: dex-tls

volumeMounts:
  - name: tls
    mountPath: /etc/dex/tls
    readOnly: true

config:
  issuer: https://my-issuer.org

  storage:
    type: memory

  enablePasswordDB: true

  grpc:
    tlsCert: /etc/dex/tls/server.crt
    tlsKey: /etc/dex/tls/server.key
    tlsClientCA: /etc/dex/tls/ca.crt

grpc:
  enabled: true
