image:
  repository: ghcr.io/philips-forks/dex
  tag: v2.41.1-hsdp.2-alpine

volumes:
  - name: tls
    configMap:
      name: dex-tls

volumeMounts:
  - name: tls
    mountPath: /etc/dex/tls
    readOnly: true

config:
  issuer: https://my-issuer.org

  storage:
    type: memory

  enablePasswordDB: true

  grpc:
    tlsCert: /etc/dex/tls/server.crt
    tlsKey: /etc/dex/tls/server.key
    tlsClientCA: /etc/dex/tls/ca.crt

  logger:
    level: "debug"
    format: "text" # can also be "json"

grpc:
  enabled: true
